// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require("prism-react-renderer/themes/github");
const darkCodeTheme = require("prism-react-renderer/themes/dracula");

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Sourcify Docs",
  tagline: "Documentation for sourcify.eth",
  url: "https://docs.sourcify.dev",
  baseUrl: "/",
  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",
  favicon: "img/favicon.ico",
  organizationName: "sourcifyeth", // Usually your GitHub org/user name.
  projectName: "sourcifyeth.github.io", // Usually your repo name.

  presets: [
    [
      "@docusaurus/preset-classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          // Please change this to your repo.
          editUrl: "https://github.com/sourcifyeth/docs",
        },
        // blog: {
        //   showReadingTime: true,
        //   // Please change this to your repo.
        //   editUrl:
        //     "https://github.com/facebook/docusaurus/edit/main/website/blog/",
        // },
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: "sourcify.eth",
        logo: {
          alt: "Sourcify logo",
          src: "img/logo.svg",
        },
        items: [
          {
            type: "doc",
            docId: "intro",
            position: "left",
            label: "Docs",
          },
          {
            href: "https://github.com/ethereum/sourcify",
            label: "GitHub",
            position: "right",
          },
          {
            href: "https://github.com/sourcifyeth/docs",
            label: "Github (Docs)",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "API",
                to: "/docs/api",
              },
            ],
          },
          {
            title: "Sourcify",
            items: [
              {
                label: "sourcify.dev",
                href: "https://sourcify.dev",
              },
              {
                label: "Github",
                href: "https://github.com/ethereum/sourcify",
              },
              {
                label: "Docs Github",
                href: "https://github.com/sourcifyeth/docs",
              },
            ],
          },
          {
            title: "Contact",
            items: [
              {
                label: "Twitter",
                href: "https://twitter.com/sourcifyeth",
              },
              {
                label: "Gitter",
                href: "https://gitter.im/ethereum/source-verify",
              },
              {
                label: "Matrix Chat",
                href: "https://matrix.to/#/#ethereum_source-verify:gitter.im",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Sourcify. Built with Docusaurus.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
      algolia: {
        // The application ID provided by Algolia
        appId: "8XS45JLX6A",

        // Public API key: it is safe to commit it
        apiKey: "691d0575a88687b7b39de22b6fb13fcb",

        indexName: "docs-sourcify",

        // Relevant for multiple languages or multiple versions. See https://docusaurus.io/docs/search
        contextualSearch: false,

        // Optional: Specify domains where the navigation should occur through window.location instead on history.push. Useful when our Algolia config crawls multiple documentation sites and we want to navigate with window.location.href to them.
        // externalUrlRegex: "external\\.com|domain\\.com",

        // Optional: Algolia search parameters
        searchParameters: {},

        //... other Algolia params
      },
    }),
  plugins: [
    // [
    //   "@docusaurus/plugin-content-docs",
    //   {
    //     // sidebars: { sidebar: [{ type: "autogenerated", dirName: "." }] },
    //     sidebarItemsGenerator: async function ({
    //       defaultSidebarItemsGenerator,
    //       ...args
    //     }) {
    //       const sidebarItems = await defaultSidebarItemsGenerator(args);
    //       return reverseSidebarItems(sidebarItems);
    //     },
    //   },
    // ],
  ],
  scripts: ["/matomo.js"],
};

// Reverse the sidebar items ordering (including nested category items)
function reverseSidebarItems(items) {
  // Reverse items in categories
  const result = items.map((item) => {
    if (item.type === "category") {
      return { ...item, items: reverseSidebarItems(item.items) };
    }
    return item;
  });
  // Reverse items at current level
  result.reverse();
  return result;
}

module.exports = config;
